### ISSUE TITLE
Preparing the new official FreeCAD Snap

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#1]
JFYI, @ppd and myself are working on getting the new official snap package working. We're trying to get it done before v0.20 release. I know there is a blocking issue[1] with LibPack. If it gets solved before we get the official Snap operating, please wait just a tiny little bit longer :pray: Thanks!

[1] https://github.com/FreeCAD/FreeCAD-LibPack/issues/3

**CC**  
@wwmayer  
@donovaly  
@yorikvanhavre  
@chennes

**Comment by luzpaz** [comment]
- [x] Change store user display name to FreeCAD [#2]
- [ ] Generate new token for uploading to snap store and add it to GitHub
- [x] Upload freecad-ppd repo contents and change all references to FreeCAD
- [ ] Archive freecad-ppd repository
- [ ] Upload freecad-ppd version telling users to please switch to the official snap
- [ ] Unlist freecad-ppd from the store

**Comment by ppd** [comment]
Thanks for syncing the repo over. We can start publishing tomorrow; I'll upload the token. Do we keep the exact same release scheme as in freecad-ppd?

**Comment by luzpaz** [comment]
> Do we keep the exact same release scheme as in freecad-ppd?

Yes, I think we should. And we also need to add @vejmarie's cloud stuff:  
`-DBUILD_CLOUD=1 -DALLOW_SELF_SIGNED_CERTIFICATE=1 -DBUILD_FEM=1`

**Comment by ppd** [comment]
@luzpaz I don't have sufficient permissions on this repo to upload secrets.

**Comment by ppd** [comment]
We should also transfer the `freecad-deps-core20` snap (https://github.com/ppd/freecad-deps-core20/) to the FreeCAD account. Can we get a separate repo for that? `freecad-realthunder` also depends on this.

**Comment by luzpaz** [comment]
What should I name it?

**Comment by ppd** [comment]
Maybe FreeCAD/freecad-deps-core20-snap

**Comment by ppd** [comment]
![image](https://user-images.githubusercontent.com/6652223/168468962-85dca0d6-7940-4378-ad4d-86f5d4249d18.png)

How about this as a prompt for freecad-ppd users? We'd publish new revisions on all channels with this (or a smiliar) prompt and then stop publishing new revisions for freecad-ppd after some time.

**Comment by luzpaz** [comment]
> Maybe FreeCAD/freecad-deps-core20-snap

Done: https://github.com/FreeCAD/freecad-deps-core20-snap

**Comment by ppd** [comment]
Alright. As I'm not a member of the FreeCAD organization on GitHub, I can't perform any admin tasks on this repo. You'll have to add the snapcraft token as a secret (named STORE_LOGIN).

**Comment by luzpaz** [comment]
I added you as a member, can you access said admin tasks?

**Comment by ppd** [comment]
Ah, very nice, yes. Thank you.

**Comment by ppd** [comment]
Okay. Before I can add the token to freecad-deps-core20, we must transfer it to the FreeCAD account. Can you do the same you did when transferring freecad?

**Comment by luzpaz** [comment]
Oh yea..that needs to be done though the Snap store right? Just a moment

**Comment by luzpaz** [comment]
> Oh yea..that needs to be done though the Snap store right? Just a moment

Done.

**Comment by vejmarie** [comment]
Just curious how many users did we had on freecad-ppd ?

**Comment by luzpaz** [comment]
![Screenshot_20220515_172524](https://user-images.githubusercontent.com/4140247/168494497-201d6b79-ff2d-4293-9133-8009bdb865ad.png)

**Comment by vejmarie** [comment]
What are the small version ? Just to let you know the original freecad snap has 40k weekly users roughly. Will be good to see the 0.20 update reaching them ;). Let me know if I can help even if my bandwidth is actually low.

**Comment by luzpaz** [comment]
The smaller versions are various edge/beta builds. Their is also the occasional experimental build based on a PR that testers can test. This is a github aciton that @ppd added called 'Publish to Branch'. I hope to extensively use this for the upcoming Toponaming merge slated for v0.21dev cycle.

![Screenshot_20220515_173537](https://user-images.githubusercontent.com/4140247/168494882-516e59bd-9813-4efa-91e2-5c8708156ece.png)

Thanks, yea we're planning to release v0.20 as the new stable when the time comes.

**Comment by vejmarie** [comment]
thanks. That make sense ;). Can you add me to the snap on snapcraft.io ?

**Comment by vejmarie** [comment]
> thanks. That make sense ;). Can you add me to the snap on snapcraft.io ?

I was meaning the new freecad. While transferring it to the community I lost access to it.

**Comment by ppd** [comment]
@luzpaz The actions work, and we have 0.19.4 in `candidate`. For me, everything works perfectly. If you give the go, we can promote it to `stable`.

**Comment by luzpaz** [comment]
I just need to transfer the [freecad-deps-core20-snap](https://github.com/FreeCAD/freecad-deps-core20-snap) over to freecad-org snap account as well. Let me do that first

**Comment by ppd** [comment]
@luzpaz Yeah, you shouldn't activate the GitHub integration. As you have it configured now, snapcraft.io builds the snap on every push to master. We want to control our builds on GitHub itself via Actions.

**Comment by luzpaz** [comment]
Thanks for the explanation and disabling it. OK. we should be good to go then.

**Comment by ppd** [comment]
0.19.4 is in stable.

**Comment by ppd** [comment]
I've added a deprecation notice to the freecad-ppd repository, unlisted the snap from the store and published new builds containing the aforementioned migration prompt.

**Comment by yorikvanhavre** [comment]
Awesome work guys!

**Comment by luzpaz** [comment]
> I've added a deprecation notice to the freecad-ppd repository, unlisted the snap from the store and published new builds containing the aforementioned migration prompt.

@ppd Excellent deprecation notice! Although I would note that on manjaro I don't need to be root to install a snap (which is what the Snap store shows  

![Screenshot_20220517_063621](https://user-images.githubusercontent.com/4140247/168792569-8158f0d2-7144-433c-8a64-d6acbc68d7af.png)

**Comment by luzpaz** [comment]
@ppd problem: #3

**Comment by ppd** [comment]
> @ppd Excellent deprecation notice! Although I would note that on manjaro I don't need to be root to install a snap (which is what the Snap store shows

This is because you're logged into the store. For snap, either being root or being logged in suffices to authorize you.

**Comment by donovaly** [comment]
Hi guys, what is the status of the project?
I informed the community about it: https://forum.freecadweb.org/viewtopic.php?p=597687#p597687

To make the FreeCAD 0.20 release I need to know when you think a snap release will be ready?

**Comment by donovaly** [comment]
We tagged today the first beta release:
https://github.com/FreeCAD/FreeCAD/releases/tag/0.20beta1

Can you please create a snap release for this?
You should be able to upload it directly to the assets of
https://github.com/FreeCAD/FreeCAD/releases/tag/0.20beta1
if not, please tell me and I will do the upload.

**Comment by ppd** [comment]
@donovaly https://github.com/FreeCAD/FreeCAD-snap/actions/runs/2398292949

This will go into the `candidate` channel. It doesn't make a lot of sense to upload it as an asset because snaps are designed to be installed via the store only. It's possible to install from a file, but the extra steps required do not really make it a sensible experience compared to choosing "candidate" in the software store app.

**Comment by donovaly** [comment]
OK, Then please give me a link that I can add to the release when the Snap build is ready.

**Comment by donovaly** [comment]
With VTK 9.x we encountered several issues. It is unfortunately not as stable as VTK 8.x was. Since we don't use the new functions of VTK 9.x, we decided to stay with VTK 8.2 for the Windows (LibPack) builds. Maybe you could do the same for Snap or should it be VTK 9.x for some reasons?

**Comment by ppd** [comment]
The snap uses what's available in the core20 (Ubuntu 20.04) repos, which is VTK 7.1.

**Comment by donovaly** [comment]
> The snap uses what's available in the core20

Does this mean you cannot freely change dependencies? For example if Ubuntu goes to Qt 6.x you cannot stay at Qt 5.15?

**Comment by ppd** [comment]
You don't have to use the repositories at all; it's possible to build everything from source. The snap is deliberately kept as lean as possible and relies on as much pre-built stuff as possible.

Qt is another story. The snap uses the kde-neon extension, which sets it up with Qt and all the little things you need to do in order to hook everything up on startup. This has tremendous advantages in terms of maintenance and also performance, as those libraries are shared between all kde-neon snaps.
This will surely start shipping Qt6 at some point in the future, but only for the core22 (~ Ubuntu 22.04) base. I think the next KDE Neon release will still also ship Qt5, so it should be a non issue in any case. But even if there were only Qt6 available for the next base release, we could keep the snap on the current core20 base till Qt6 support is mature in FreeCAD.

**Comment by donovaly** [comment]
Thanks for explanation.

The build is now ready: https://github.com/FreeCAD/FreeCAD-snap/actions/runs/2398292949
Where is it now transferred? (I would need a more meaningful URL than 2398292949 ;-) )

**Comment by ppd** [comment]
> Where is it now transferred? (I would need a more meaningful URL than 2398292949 ;-) )

It's now available in the Snap Store @ https://snapcraft.io/freecad in channel `candidate`.
Or via the CLI:
```
sudo snap install freecad --candidate
```

**Comment by donovaly** [comment]
I either need a link that directly points to the file or the file itself.
I cannot just download the file from the website nor am I able to get a direct link to it.

Since I am Win-only, I cannot use snap to download the file.

(by the way, I find the Cookie settings of snapcraft quite aggressive)

**Comment by donovaly** [comment]
Can you therefore please put the snap package either here:
https://github.com/FreeCAD/FreeCAD-snap/releases
or here:
https://github.com/orgs/FreeCAD/packages?repo_name=FreeCAD-snap

**Comment by luzpaz** [comment]
I'll take care of that

**Comment by ppd** [comment]
@luzpaz Can you do it? I'm on mobile data for the whole day.

**Comment by luzpaz** [comment]
I'll take a shot

**Comment by luzpaz** [comment]
What should the release name be?

**Comment by luzpaz** [comment]
![Screenshot_20220528_075416](https://user-images.githubusercontent.com/4140247/170824420-75d66ec5-794b-4198-992f-cca11c241cd7.png)
On 2nd thoughts, I've added a note to the FreeCAD release page. It doesn't make sense to point to a snap package. We just have users download directly from the CLI like they're used to.

**Comment by donovaly** [comment]
OK, thank you.
