### ISSUE TITLE
Document freecad-deps-core20

### ISSUE THREAD

**Issue by ppd** [FreeCAD/FreeCAD-snap#10]
Explain the role of the dependencies snap freecad-deps-core20 (https://github.com/FreeCAD/freecad-deps-core20-snap/) somewhere in the docs.

**Comment by AjinkyaDahale** [comment]
There seems to be an issue here currently. When trying to install on Ubuntu 22.04 I get this:
```
error: cannot perform the following tasks:
- Ensure prerequisites for "freecad" are available (cannot install prerequisite "kde-frameworks-5-96-qt-5-15-5-core20": no snap revision available as specified)
```

Is this related?

**Comment by luzpaz** [comment]
I wish @ppd updated the docs for this. Not sure what to do. Any suggestions ?

**Comment by luzpaz** [comment]
I've merged #80 (props to @riqueenz). Lets see if this helps.

**Comment by chennes** [comment]
I've added a note about that repo to the Developer's Handbook page on Snaps.

**Comment by luzpaz** [comment]
Link ?

**Comment by chennes** [comment]
https://github.com/FreeCAD/DevelopersHandbook/blob/master/technical/snap.md
