### ISSUE TITLE
Cannot switch from edge to stable channel

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD-snap#105]
I've been using the edge channel for a while, until I've hit on a few regressions and decided to go back to the stable channel. When trying to do so on the command line, I'm getting this error:

```
snap refresh freecad --channel=stable
error: cannot perform the following tasks:
- Setup snap "freecad" (759) security profiles (cannot update mount namespace of snap "freecad": cannot update preserved namespace of snap "freecad": cannot update snap namespace: cannot create symlink in "/usr/share/libdrm/amdgpu.ids": existing file in the way)
```

The only workaround I could find was to remove the freecad snap alltogether and reinstall from the stable channel from scratch.

**Comment by p-himik** [comment]
Just stumbled upon this as well. Not an expect on snaps, but it seems that `snapcraft.yml` mentions files that come not from snap dependencies of the snap package for FreeCAD, but rather from the system. An attempt to downgrade the snap tries to do something with the files mentioned in the `layout` section.
It's not just the aforementioned `/usr/share/libdrm/amdgpu.ids` that on my system comes from an installed `libdrm-common`. When I renamed that file just to see what happens, I got a different error:
```
error: cannot perform the following tasks:
- Setup snap "freecad" (759) security profiles (cannot update mount namespace of snap "freecad": cannot update preserved namespace of snap "freecad": cannot update snap namespace: remove /usr/bin/mpirun: no such file or directory)
```
No clue why it says "no such file" given that it exists and at least on my machine `/usr/bin/mpirun` is handled by the Ubuntu's alternatives system and is a symbolic link to `/etc/alternatives/mpirun`, which in turn is a symbolic link to `/usr/bin/mpirun.openmpi` that comes from `openmpi-bin`. Seems to be related to #100, not sure.

But at least reinstalling the package worked, although it took quite a bit of time.

**Comment by luzpaz** [comment]
is this still an issue ?

**Comment by p-himik** [comment]
Doesn't seem like it - I just tested and was able to switch to edge and back to stable. FreeCAD is running fine from either of the channels.

**Comment by luzpaz** [comment]
Lets close. If this still rears it's head, feel free to notate the ticket and we can re-open it.
