### ISSUE TITLE
Add cups-control package?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#11]
Per user 'sombrero' in https://forum.freecadweb.org/viewtopic.php?p=598166#p598166
> no printers are recognised, only print to file is available in the dialogue.

User made a comparison between gimp and freecad snaps and concluded that 'cups-control' package was missing from freecad snap.

**Comment by ppd** [comment]
Yeah, sure. Makes sense. Cups-control is deprecated for printing, I think; there's a better interface now.
