### ISSUE TITLE
Snap build failed: Exported credentials are no longer valid for the Snap Store

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD-snap#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Publishing the latest daily snap package build failed with:

```
Exported credentials are no longer valid for the Snap Store.
Recommended resolution: Run export-login and update SNAPCRAFT_STORE_CREDENTIALS.
For more information, check out: https://snapcraft.io/docs/snapcraft-authentication
Full execution log: '/home/runner/.local/state/snapcraft/log/snapcraft-20240[8](https://github.com/FreeCAD/FreeCAD-snap/actions/runs/10240590888/job/28327659024#step:5:9)05-020312.844130.log'
```

Log: https://github.com/FreeCAD/FreeCAD-snap/actions/runs/10240590888/job/28327659024

### Full version info

```shell
N/A
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by furgo16** [comment]
@luzpaz, @yorikvanhavre, or @chennes, has anyone of you been able to look into updating the credentials to resume the daily builds? Is there anything I could do to help? Thanks!

**Comment by luzpaz** [comment]
i have access to the store but i don't have the snap installation on this machine. The changes need to be done via the CLI if I understand correctly? I looked at the website interface and couldn't figure out if there was an alternate  way to do it that way?

**Comment by chennes** [comment]
I just generated new credentials and uploaded them. Assuming I didn't bork it up along the way, the new snap should be ready shortly.
