### ISSUE TITLE
Libraries information cant be seen at snap dev version (due to `ThirdPartyLibraries.html` not installing correctly)

### ISSUE THREAD

**Issue by projectcad** [FreeCAD/FreeCAD-snap#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Libraries information cant be seen at  snap dev version 

![freecad_snap_about](https://github.com/user-attachments/assets/d4fd4a63-f420-43f2-9018-1da671324f39)

### Full version info

```shell
OS: Ubuntu Core 22 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.39241 (Git) Snap 1198
Build type: Release
Branch: main
Hash: cdb92768fe4f33d900664415c613f9eced5b8927
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/unset/Qt default
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by furgo16** [comment]
See https://github.com/FreeCAD/FreeCAD-snap/issues/141#issuecomment-2565375941. Perhaps a missing file not being included in the snap package?

**Comment by luzpaz** [comment]
In main there is a cmake file that directs the installation of this file:  
https://github.com/FreeCAD/FreeCAD/blob/main/src/Doc/ThirdPartyLibraries.html.cmake

Need to check if this is missing.

**Comment by luzpaz** [comment]
> file:////snap/freecad/1234/usr/share/doc/FreeCAD//ThirdPartyLibraries.html
I just searched my `/snap/freecad/1234/usr/share/doc` and there is no FreeCAD subdirectory in there. So we know that `/snap/freecad/1234/usr/share/doc` is legit and the place the snap is pointing to.

**Comment by luzpaz** [comment]
Where does the flatpak install `ThirdPartyLibraries.html` to ?  
Any idea @adrianinsaval

**Comment by adrianinsaval** [comment]
> Where does the flatpak install `ThirdPartyLibraries.html` to ? Any idea @adrianinsaval

/app/share/doc/FreeCAD/ThirdPartyLibraries.html

> Looks like the directory it's installed into via cmake on Fedora gets removed

it probably shouldn't be, this was also a problem some time ago in the windows weekly and I had to make sure the files are shipped: https://github.com/FreeCAD/FreeCAD-Bundle/commit/7ce40833dc47100438d96d40ae28dd1d1613d3b2

I don't know if the fedora spec stuff is well maintained anymore

**Comment by adrianinsaval** [comment]
this line should be adjusted or removed to make sure the file is being shipped. I don't understand why we ever wanted to remove license files anyways sounds top me like that is on the edge of being a license violation
https://github.com/FreeCAD/FreeCAD-snap/blob/9be8df14e4744f06b42a55b4a786fa90f6099919/snap/snapcraft.yaml#L323

**Comment by luzpaz** [comment]
Fixed in https://github.com/FreeCAD/FreeCAD-snap/commit/392dca0ed3f16125019f681be7fefa121df4d753
