### ISSUE TITLE
Add CADcloud cmake logic

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#17]
@vejmarie could you make a PR for CADcloud related logic to be available in the v0.20 build ?

**Comment by ppd** [comment]
Does this only need the build options described here: https://github.com/FreeCAD/FreeCAD-snap/issues/1#issuecomment-1126786517?

**Comment by furgo16** [comment]
From the linked comment, reportedly there was a need to add these CMake build flags:

```
-DBUILD_CLOUD=1
-DALLOW_SELF_SIGNED_CERTIFICATE=1
-DBUILD_FEM=1
```

@luzpaz do you happen to know,

- Why the flags were needed in the first place?
- Are they still needed?

Since it seems no users have complained about this in two years, perhaps we can close it?

**Comment by furgo16** [comment]
Ok, I see now what CADCloud is: https://forum.freecad.org/viewtopic.php?t=51035, https://github.com/opencomputeproject/CADCloud

Given that the author is no longer active in GitHub, and that the project has not had any updates in the last three years, it might be safe to close it.
