### ISSUE TITLE
Publisher name should be "FreeCAD"

### ISSUE THREAD

**Issue by ppd** [FreeCAD/FreeCAD-snap#2]
At the moment we have

```shell
name:    freecad
summary: This is the freecad 0.19 release supporting OCCT 7 / Netgen and many
  other features
publisher: kunda1
store-url: https://snapcraft.io/freecad
contact:   luzpaz@freecad.org
license:   LGPL-2.0
```
It should be: "FreeCAD"

You should be able to edit it on https://snapcraft.io/account/details

**Comment by luzpaz** [comment]
Done

**Comment by ppd** [comment]
Hm. It still displays "kunda1" here: https://dashboard.snapcraft.io/snaps/freecad/ and on the store. Maybe it takes a while to propagate.
