### ISSUE TITLE
v0.20 Released

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#21]
https://github.com/FreeCAD/FreeCAD/releases/tag/0.20

**Comment by ppd** [comment]
https://github.com/FreeCAD/FreeCAD-snap/commit/94a420e4de3f288c70b0dca0c8a63dcb8938c7ea
Will appear in candidate. If everything works, we'll push it to stable.

**Comment by ppd** [comment]
Do we request a 0.19 track and keep the older release there?

**Comment by ppd** [comment]
0.20 is now in stable.
