### ISSUE TITLE
Mention in https://wiki.freecad.org/Installing_on_Linux

### ISSUE THREAD

**Issue by ppd** [FreeCAD/FreeCAD-snap#23]
> Experimental [Personal Package Archive](https://help.ubuntu.com/community/PPA) (PPA) repositories, [AppImages](https://wiki.freecad.org/AppImage), and [Ubuntu Snaps](https://wiki.freecad.org/Ubuntu_Snap) for testing bleeding-edge features.

Most use the snap stable releases, so the page should probably reflect the fact that snaps aren't experimental per se.

**Comment by luzpaz** [comment]
Suggestions?

**Comment by ppd** [comment]
I think it has one closing bracket too many: `[Ubuntu_Snap|Snap packages]]`

**Comment by luzpaz** [comment]
OK, another wiki editor got to it before me. Closing
