### ISSUE TITLE
Create 'toponaming' Snap channel

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#24]
Target: https://github.com/FreeCAD/FreeCAD/tree/development/toponaming

The function of the snap will be to build a nightly Snap that allows testers to test any of the commits made to the `development/toponaming` branch.

CC
@yorikvanhavre   
@donovaly  
@wwmayer  
@realthunder
@looooo 
@adrianinsaval

**Comment by ppd** [comment]
Do you want to request an entirely new track in addition to `latest`? Or do you want to "abuse" the branch system an publish it to `latest/edge/toponaming`?

**Comment by ppd** [comment]
I think the branch option is better because it's meant for testing, and not as a track for prolonged use. That should be reserved for either staging versions, such as Visual Studio Code's `insiders` track, or old stable versions, such as in the `node` (Node.js) snap.

**Comment by luzpaz** [comment]
@ppd please review the documentation I added for this in https://wiki.freecad.org/Ubuntu_Snap#Changing_between_different_Snaps 
TIA!

**Comment by ppd** [comment]
Looks good! Maybe simplify it by only mentioning refresh. Almost everyone wants to switch and refresh at the same time.

**Comment by luzpaz** [comment]
@ppd how does one find the FreeCAD toponaming snap channel ?  It's `latest/edge/toponaming` but is it listed anywhere ?

**Comment by ppd** [comment]
It's not listed:

> Branch names convey their purpose, such as fix-for-bug123, but the name isn’t exposed in the normal way, such as with snap info. Instead, they can only be installed by someone who knows the branch name, and this is usually only shared by the snap developer to test a specific fix or release.

(https://snapcraft.io/docs/channels)

**Comment by luzpaz** [comment]
Ok. In that case a dedicated forum thread has been created: https://forum.freecadweb.org/viewtopic.php?f=44&t=71687
