### ISSUE TITLE
shared config folder betweeen appimage and snap FreeCAD packages

### ISSUE THREAD

**Issue by bambukouk** [FreeCAD/FreeCAD-snap#25]
https://forum.freecadweb.org/viewtopic.php?f=3&t=69534

I am not getting much traction the forum...
(have asked similar question before https://forum.freecadweb.org/viewtopic.php?f=3&t=68643 again with no solution)

so in desperation I am bothering @ppd you here (sorry)

Is there a way to keep configuration of an appimage FreeCAD package and snap FreeCAD package the same?

**Comment by ppd** [comment]
If you can set environment variables for both, you could set FREECAD_USER_DATA to the same directory. The directory must be accessible for the snap though, so it shouldn't be in a hidden top level directory under $HOME. E.g. /home/user/FreeCAD would work.

**Comment by bambukouk** [comment]
Thank you!
I started reading...
![env_variables](https://user-images.githubusercontent.com/50301871/174340366-46a878d7-447b-42ae-9eba-e24c7c508142.png)

Not quite clear how to go about changing things... I assume it is something like this?:
![change_settings](https://user-images.githubusercontent.com/50301871/174340841-edb95b0c-af10-483e-8661-778a8422209b.png)

I think I have a headache .... will take a rest now :+1:

**Comment by ppd** [comment]
If you have desktop files for your AppImage & Snap installations, you can modify them to have them set the environment variables:
https://wiki.archlinux.org/title/desktop_entries#Modify_environment_variables

Use FREECAD_USER_DATA because the snap overwrites FREECAD_USER_HOME.

**Comment by bambukouk** [comment]
That was the bit I was missing 👍
Yes, I have both .desktop files (having created appimage one myself, and having copied snap one to create OS integration) so should be able to do something.
Will play with it over weekend and let you know the result.

Thank you again!
