### ISSUE TITLE
fcFEM dependencies: sksparse

### ISSUE THREAD

**Issue by HarryvL** [FreeCAD/FreeCAD-snap#30]
fcFEM ... could you please add sksparse to the dependencies? Tx.

**Comment by ppd** [comment]
This package: https://scikit-sparse.readthedocs.io/en/latest/overview.html, correct?

**Comment by luzpaz** [comment]
@HarryvL :point_up_2:

**Comment by HarryvL** [comment]
That's the one !

**Comment by ppd** [comment]
@HarryvL please try channel `latest/edge/sksparse`:

```shell
snap refresh freecad --channel='latest/edge/sksparse'
```

**Comment by HarryvL** [comment]
Perfect. Everything seems to work. Thanks for the effort !
