### ISSUE TITLE
error on: raise SystemExit()

### ISSUE THREAD

**Issue by HarryvL** [FreeCAD/FreeCAD-snap#34]
Hi, I have a few `raise SystemExit()` calls in my macro code, but since I started to use the snap I get: `<class 'TypeError'>: bad argument type for built-in operation`. Is there a simple way to resolve this?

**Comment by HarryvL** [comment]
I have narrowed it down to those locations in my code, but the error message makes no sense. I will continue testing.

**Comment by HarryvL** [comment]
PS: normally I get more info (like line number etc), but this error comes in isolation, without any further info.

**Comment by ppd** [comment]
According to the error, it seems like you're passing an object to a function that expects a specific, different type. A common source of such errors is code dealing with paths. Maybe you're passing a path object to somewhere that expects a string or vice versa.
