### ISSUE TITLE
Build reporting `libpsm-infinipath1` should be added to .yaml but it's already there

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#37]
Per https://github.com/FreeCAD/FreeCAD-snap/runs/7169358403?check_suite_focus=true#step:6:13721
```
The 'freecad' part is missing libraries that are not included in the snap or base. They can be satisfied by adding the following entries to the existing stage-packages for this part:
- libpsm-infinipath1
```
But `libpsm-infinipath1` already exists https://github.com/FreeCAD/FreeCAD-snap/blob/1f71ac161140abb0694b6e4e98d1732c8eb3d42c/snap/snapcraft.yaml#L201

So I'm confused as to what's the issue?

**Comment by ppd** [comment]
Seems to be a snapcraft issue. Maybe it has to do with our cleanup step. In any case, it doesn't really matter.
