### ISSUE TITLE
Feature: Trigger builds (edge/experimental) via some sort of github bot   

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#39]
It would be great to be able to automate some of the following redundant tasks:

- [ ] Trigger an 'edge' build from within the FreeCAD issue queues using a trigger word
- [ ] Trigger a 'Publish to Branch' build from within the FreeCAD issue queues using a trigger word
- [ ] Have a bot listen for commits made to a PR or specific FreeCAD cloned repo and generate a new build for each new commit

**Comment by ppd** [comment]
The obvious solution is to integrate the snap packaging and associated GitHub actions into the FreeCAD repository. I'm not sure that this is desirable. 

Another option is to introduce a suitable Action in the upstream repo that triggers a `repository_dispatch` event in this repo: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
You could write an action that listens to the triggers you described and fires this event via curl on FreeCAD-snap.

The last option would be to create some unholy polling solution that tries to do this without integrating anything into the upstream repository. This would be unwise and likely break often.

**Comment by luzpaz** [comment]
@ppd thanks for the elaborations!  
@yorikvanhavre would you be OK with something like this?

**Comment by yorikvanhavre** [comment]
Yes! There is no harm for FreeCAD itself to have a special keyword, and I guess it's easy to catch with GH actions. Maybe also a more "formal" and tracable way could be to tag commits we want an edge build for, but maybe best to start simple and see if we need more later.

**Comment by ppd** [comment]
A fourth, more clever approach would be: Publish PRs from this repository as `latest/edge/pr-$id`. In this way, authors could also add dependencies or make other necessary changes to the snapcraft recipe.
The author would branch master from this repo, change the source to their branch of FreeCAD, and choose when to publish by adding a trigger commit to their PR on FreeCAD-snap (e.g. by incrementing an integer in a random file).

As the author necessarily must have access to the snapcraft secret in their GitHub action, such PRs must be vetted first to make sure the authors are trustworthy. GitHub already has such a function.

**Comment by ppd** [comment]
The fourth option has been implemented in https://github.com/FreeCAD/FreeCAD-snap/commit/8b4b73d65c0218afd99ded0b1bdde71a840959cc (see commit message for details/instructions).

**Comment by luzpaz** [comment]
![chris-pratt](https://user-images.githubusercontent.com/4140247/178564485-7c0e2bf0-46da-43bf-ae24-2721b0ca984c.gif)

**Comment by ppd** [comment]
@luzpaz Just so you're aware:

> After 30 days with no further updates, a branch will be closed automatically. The replacement snap will then be chosen as it would be with closed channels (see below). For example, beta/fix-for-bug123 will fall back to beta after the fix-for-bug123 branch is closed.

(https://snapcraft.io/docs/channels)
