### ISSUE TITLE
Add RapidJSON for glTF export

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#4]
https://forum.freecadweb.org/viewtopic.php?p=595797#p595797

**Comment by ppd** [comment]
This needs to added in https://github.com/ppd/freecad-deps-core20

**Comment by ppd** [comment]
https://github.com/FreeCAD/freecad-deps-core20-snap/actions/runs/2353775168

**Comment by ppd** [comment]
It's in stable. Will appear in the next edge release.

**Comment by ppd** [comment]
I consider this closed. I have no way to test it myself, but I see no reason why it wouldn't have worked.
