### ISSUE TITLE
Track strategy

### ISSUE THREAD

**Issue by ppd** [FreeCAD/FreeCAD-snap#5]
https://snapcraft.io/docs/channels

Snaps are release to channels, which have the format `<track>/<risk>/<branch>`.
The default track is `latest`, which is what we're using for the current stable release as `latest/stable`.

It is possible to request more tracks, which is commonly used to release multiple supported stable versions.
For FreeCAD, this could mean creating a `0.19` track which retains the `0.19.4` release when `latest` inevitably switches to the new `0.20` release.

Is that something we possibly want and can support?

**Comment by luzpaz** [comment]
Cool stuff!  
If I understood correctly then I'm not sure some users would appreciate the automated update from 0.19.4 to 0.20

**Comment by luzpaz** [comment]
Forgot about this. Are you closing it due to inactivity?

**Comment by ppd** [comment]
Yes. The demand isn't that high, and the less there is to support, the better.
