### ISSUE TITLE
missing module(s) cant find 3dmodels dir

### ISSUE THREAD

**Issue by SpeedrunnerG55** [FreeCAD/FreeCAD-snap#54]
when I try to configure kicad step up to use my kicad 3dmodels directory, it is unable to see any of the contents in the /usr directory, and I think has some permissions issue.

![image](https://user-images.githubusercontent.com/9276267/186002366-6b51a6c9-74d5-4a57-8dbc-45e09d9f836d.png)

apparently, snap apps are restricted from full file system access. 🤷

![image](https://user-images.githubusercontent.com/9276267/186001507-2dfe10ec-74b6-473c-abb9-5aec0a71ae88.png)

https://github.com/easyw/kicadStepUpMod/issues/145 - reference to the same issue, I updated to ubuntu 22.04 since I posted there and I am still affected.

```
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git) Snap 161
Build type: Release
Branch: tag: 0.20
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.8.10, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.2
Locale: English/United States (en_US)
Installed mods: 
  * kicadStepUpMod 10.14.5
```

```
Application: KiCad

Version: 6.0.2+dfsg-1, release build

Libraries:
	wxWidgets 3.0.5
	libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.12

Platform: Linux 5.15.0-46-generic x86_64, 64 bit, Little endian, wxGTK, ubuntu-xorg, x11

Build Info:
	Date: Feb 12 2022 09:36:02
	wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
	Boost: 1.74.0
	OCC: 7.5.1
	Curl: 7.81.0
	ngspice: 36
	Compiler: GCC 11.2.0 with C++ ABI 1016

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

**Comment by ppd** [comment]
Yes, the snap runs confined: https://snapcraft.io/docs/snap-confinement
So that's working as intended.

You can create a bind mount in your home directory that points to your kicad stuff. FreeCAD will be able to see it then.
