### ISSUE TITLE
Snap: Add pycollada to snapcraft

### ISSUE THREAD

**Issue by rydb** [FreeCAD/FreeCAD-snap#73]
the export to .dae functionality for FreeCAD requires collada from pycollada. Can y'all add pycollada to the snapcraft? I learned you can install it with freecad.pip, but I had to find this repo before I found that out.

**Comment by luzpaz** [comment]
Sorry this took so long, @rydb.

**Comment by luzpaz** [comment]
Reopening due to: 

> Failed to fetch stage packages: Error downloading packages for part 'freecad': The package 'pycollada' was not found..
Error: Process completed with exit code 2.

https://github.com/FreeCAD/FreeCAD-snap/actions/runs/4565089164/jobs/8055708513#step:4:2546

**Comment by luzpaz** [comment]
@ScarlettGatelyMoore do you have time to tackle this ?

**Comment by chennes** [comment]
The dependency on core22 is `python3-collada`, I think. I'll try to add it.

**Comment by chennes** [comment]
OK, that dependency should be in the daily now -- @rydb can you give it a try?

**Comment by luzpaz** [comment]
For posterity: c27d932703ee622a95fb0ee0a2ea7d89bca073e7

**Comment by furgo16** [comment]
I can also confirm that this is working: pycollada is already in the snap and there is no need to install it manually afterwards. DAE import works out of the box.

To maintainers, I think this issue can be closed. Thanks!

**Comment by EwingKang** [comment]
On my Ubuntu 22.04 deskop, after `sudo snap install freecad`, the freeCAD v0.21.1 33268+26 is still showing 
> pycollada not found, collada support is disabled

**Comment by furgo16** [comment]
@luzpaz if pycollada is not going to be backported to the 0.21 snap, can this issue be closed?
