### ISSUE TITLE
Updating stable release to v0.20.2

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#74]
@adrianinsaval I'm going to try updating Snap stable. Are there any nuances I should be aware of before I change the target tag to v0.20.2 ? (that you may have encountered with flatpak or Arch AUR ?)

**Comment by luzpaz** [comment]
Update: Still trying to figure out how to push v0.20.2 candidate to stable.

**Comment by luzpaz** [comment]
Nevermind, I figured how to promote it to stable. I need login to snapcraft (https://snapcraft.io/freecad/releases) and click 'Promote' on the candidate build.

**Comment by luzpaz** [comment]
Closing

**Comment by adrianinsaval** [comment]
thanks!
