### ISSUE TITLE
Make sure realthunder's snap points to correct official FreeCAD snap

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#77]
@realthunder do you mind amending the README info for https://snapcraft.io/freecad-realthunder ? 

It currently shows this:

![Screenshot_20221231_180017](https://user-images.githubusercontent.com/4140247/210157102-2fce494a-83a7-4aa1-98b4-a6ee8cf13636.png)

It should read: 
`If you are looking for upstream FreeCAD snap image, the official release is at https://snapcraft.io/freecad`

**Comment by luzpaz** [comment]
@realthunder ping

**Comment by realthunder** [comment]
Changed. Sorry for the delay.

**Comment by luzpaz** [comment]
Thx!
