### ISSUE TITLE
Snap: Update Github Actions to node16

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#79]
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by luzpaz** [comment]
@riqueenz do you have any experience with this ?

**Comment by luzpaz** [comment]
@riqueenz ppd's been awol so we have to do figure this out ourselves

**Comment by luzpaz** [comment]
@chennes sorry to bug but this issue has been pending as well and I'm not certain how to solve it.

**Comment by chennes** [comment]
I'll take care of it when I upgrade to core22.

**Comment by chennes** [comment]
I've updated all actions to use actions/checkout@v3, which resolves this.
