### ISSUE TITLE
Use blobfish patched OCC version

### ISSUE THREAD

**Issue by adrianinsaval** [FreeCAD/FreeCAD-snap#8]
as explained here: https://forum.freecadweb.org/viewtopic.php?f=10&t=66407&start=100#p597687
it would be ideal to use the blobfish patched occ (https://gitlab.com/blobfish/occt/-/tree/V7_6_2_BF) instead of the official one for FreeCAD, could you switch to this url?

**Comment by ppd** [comment]
https://github.com/FreeCAD/freecad-deps-core20-snap/actions/runs/2397739621

**Comment by adrianinsaval** [comment]
thanks!
