### ISSUE TITLE
Snap: Add fmt dependency

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#82]
https://github.com/FreeCAD/FreeCAD-Bundle/pull/160  

Edit: need to find where to add this dependency in the snap building process

**Comment by adrianinsaval** [comment]
no real need to do this since the snap build process has access to the internet so freecad auto fetches the required sources and builds it, if that wasn't the case the build would have been failing.

**Comment by yorikvanhavre** [comment]
So this can be closed?

**Comment by adrianinsaval** [comment]
Yes
