### ISSUE TITLE
Documentation: how to check if a 3rd party depedency is available

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#83]
Different package ecosystems name their dependencies differently. 

1. Where does Snap pull dependencies from ?  
2. How does one query to ascertain the correct name of the dependency ?

**Comment by luzpaz** [comment]
Answers:
1. Dependencies are listed using their apt package names and are retrieved from the set of repositories officially supported by the distribution (make sure you pulling an apt package for the correct distro version that the snap packaging is utilizing.
2. https://packages.ubuntu.com

**Comment by luzpaz** [comment]
Related to #82

**Comment by chennes** [comment]
Can you edit the Handbook to include this piece of info?
