### ISSUE TITLE
Remove Raytracing from `snapcraft.yml` as it has been removed from FreeCAD core

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-snap#84]
`snapcraft.yml`: https://github.com/FreeCAD/FreeCAD-snap/blob/98c21cdff33c02a0e9a484bc5f9bf0aa4434f5d7/snap/snapcraft.yaml#L58-L59

FreeCAD core: https://github.com/FreeCAD/FreeCAD/pull/9420

**Comment by malix0** [comment]
Is this still valid? I ask because at the moment there are no change to snapcraft.yml

**Comment by chennes** [comment]
It's still valid, I just haven't done it yet.

**Comment by luzpaz** [comment]
Done in eb7537d4abf735ffb94e723e4e88a3ab722446bc
