### ISSUE TITLE
Please update to core22 to use the kde-neon extension

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [FreeCAD/FreeCAD-snap#86]
Core20 is no longer supported for the kde-neon extension as we have no way to security updates. I am more than happy to help here.
Thanks,
Scarlett

**Comment by luzpaz** [comment]
Thank you for the offer! We will take you up on it!

**Comment by ScarlettGatelyMoore** [comment]
Ok, forking and will do a PR

**Comment by ScarlettGatelyMoore** [comment]
Sorry, slight delay while I wait for a PR to get merged in snapcraft. Still on my TO-DO!

**Comment by luzpaz** [comment]
TIA, really appreciate any help with this!

**Comment by chennes** [comment]
I'm in the process of trying to get freecad-deps updated to core22, I am assuming that is a prerequisite for updating this one to core22 as well?

**Comment by luzpaz** [comment]
Ping @ScarlettGatelyMoore

**Comment by ScarlettGatelyMoore** [comment]
> I'm in the process of trying to get freecad-deps updated to core22, I am assuming that is a prerequisite for updating this one to core22 as well?

Yes I imagine it is. Please let me know if you need help or finish it and I will get this done. The PR I was waiting for has finally gone through.

**Comment by malix0** [comment]
Hi, I'm waiting for FreeCAD 0.21 snap release, if I can help in some way, I'll try to do my best

**Comment by ScarlettGatelyMoore** [comment]
> @ScarlettGatelyMoore I was hoping it was just a matter of switching core20 to core22 in that repo (it's pretty simple otherwise), but the build timed out on the runner after six hours. So I tried building it locally and I get a strange missing library failure when building OCCT (the library is present where I expect it when examining the failure with `snapcraft --debug`. If you've got time to look into switching FreeCAD-deps-snap (the core22 branch) to core22 I'd appreciate any help you can provide.

Here is my PR https://github.com/FreeCAD/freecad-deps-snap/pull/2

The only thing that fails for me is the version part, so it is commented.

**Comment by chennes** [comment]
> Hi, I'm waiting for FreeCAD 0.21 snap release, if I can help in some way, I'll try to do my best

The 0.21 snap is released, you should have access to it in the stable channel.

**Comment by chennes** [comment]
> Here is my PR [FreeCAD/freecad-deps-snap#2](https://github.com/FreeCAD/freecad-deps-snap/pull/2)

OK, it took me a few tried, but I've now got those core22 deps installed as a private snap package. So the next step is to upgrade this one to core22, along with whatever other library dependencies that entails. Do you have time to look at that, @ScarlettGatelyMoore ?

**Comment by ScarlettGatelyMoore** [comment]
Hi,
A quick look and it looks like the     
build-snaps:
      - freecad-deps-core20
    stage-snaps:
      - freecad-deps-core20

Needs fixing in the snap store first. Do you have the powers to upload that private freecad-deps-core22 snap we just worked on to the store and make it public? This snap depends on it and won't build without it.

**Comment by ScarlettGatelyMoore** [comment]
https://github.com/FreeCAD/FreeCAD-snap/compare/master...ScarlettGatelyMoore:FreeCAD-snap:master
 Is what I have so far, I can't test it until freecad-deps-snap is updated in the snap store.

**Comment by chennes** [comment]
Sorry, I didn't see that I could switch to "unlisted" from "private", but only *after* I created the snap. That's done now, you should be able to access freecad-deps-core22

**Comment by ScarlettGatelyMoore** [comment]
Great! I should be able to wrap this up and do a PR tomorrow.

**Comment by ScarlettGatelyMoore** [comment]
Here you go:
https://github.com/FreeCAD/FreeCAD-snap/pull/92

**Comment by chennes** [comment]
Can you take a look at the error in this Actions run? I don't know why it's failing... https://github.com/FreeCAD/FreeCAD-snap/actions/runs/5827731613/job/15804251434

**Comment by ScarlettGatelyMoore** [comment]
> Can you take a look at the error in this Actions run? I don't know why it's failing... https://github.com/FreeCAD/FreeCAD-snap/actions/runs/5827731613/job/15804251434

Apologies, I was working in the snap directory, I have fixed it now with the full path and should fix the error

**Comment by ScarlettGatelyMoore** [comment]
https://github.com/FreeCAD/FreeCAD-snap/pull/93

**Comment by chennes** [comment]
This is working now, thanks for the assist @ScarlettGatelyMoore !!

**Comment by luzpaz** [comment]
Indeed, thank you very much @ScarlettGatelyMoore !!
