### ISSUE TITLE
Beta- & edge-channels don't get updated

### ISSUE THREAD

**Issue by Glitchy-Tozier** [FreeCAD/FreeCAD-snap#90]
See this thread: https://forum.freecad.org/viewtopic.php?t=79724

```
$ snap info freecad

name:      freecad
summary:   An open source parametric 3D CAD modeler
publisher: FreeCAD (freecad-org)
store-url: https://snapcraft.io/freecad
contact:   https://forum.freecad.org/viewtopic.php?f=42&t=68714
license:   LGPL-2.0-or-later
description: |
  FreeCAD is a parametric 3D modeler. Parametric modeling
  allows you to easily modify your design by going back into
  your model history and changing its parameters. FreeCAD is
  open source (LGPL license) and completely modular, allowing
  for very advanced extension and customization.
  
  FreeCAD is multiplatfom, and reads and writes many open
  file formats such as STEP, IGES, STL and others.
  
  **Channels**
  
  There are three maintained channels for this snap:
  
  - `stable` contains the latest upstream release, i.e. the most recent
  tagged commit.
  (**Use this if you don't know what you're doing.**)
  - `beta` contains automated weekly promotions from `edge`.
  (**Use this if you want edge with fewer updates.**)
  - `edge` contains automated (daily) builds from the latest master commit.
  (**Use this to test new features. Might be unstable.**)
  
  **Apps/Commands**
  
  There are multiple apps/commands included in the snap:
  
  - `freecad`:               Run FreeCAD
  - `freecad.cmd`:      Run FreeCAD command line interface
  - `freecad.pip`:        Install python packages for user (not system-wide).
                         E.g. `freecad.pip install py_slvs` for Assembly3.
  
  
  Side note: There is a FreeCAD experimental branch called 'Link branch'
  created by a user named 'realthunder' that has become popular. It is
  available as a Snap package named `freecad-realthunder`
  (https://snapcraft.io/freecad-realthunder).
commands:
  - freecad.cmd
  - freecad
  - freecad.pip
snap-id:      6gjU50q0lEDaMTtSUxYoVDSmjR5fERpB
tracking:     latest/edge
refresh-date: 37 days ago, at 10:18 CEST
channels:
  latest/stable:    0.20.2         2022-12-31 (517) 577MB -
  latest/candidate: 0.20.2         2022-12-28 (517) 577MB -
  latest/beta:      0.21-g14dd2c60 2023-06-11 (726) 587MB -
  latest/edge:      0.21-g14dd2c60 2023-06-09 (726) 587MB -
installed:          0.21-g14dd2c60            (726) 587MB -
```

**Comment by luzpaz** [comment]
Indeed. Snap core and dependencies need to be looked at:
https://github.com/FreeCAD/FreeCAD-snap/pull/80#issuecomment-1568400556

**Comment by chennes** [comment]
Working on it right now -- I hope to have the snaps back to normal functionality by tomorrow.

**Comment by chennes** [comment]
@luzpaz I'm going to need your help to do it, we need to generate a new key for the snapcraft store and as far as I know you are the only one with access.

**Comment by luzpaz** [comment]
@chennes i'm trying to figure out how to add you as a maintainer as well. It doesn't seem like it can be done through the snapcraft website. I'm having issues with my machine and don't have access to my ssh credentials ATM.

**Comment by chennes** [comment]
No worries, it turns out Yorik had access. I'm still fighting with the GitHub runners, but I should be able to get this resolved soon. The only problem is how much time the runners take (two hours), which slows down fixing any issues.

**Comment by luzpaz** [comment]
Great news!

> The only problem is how much time the runners take (two hours), which slows down fixing any issues.  

Indeed. It would be nice if someone dug deeper to see if the build process can be optimized.

**Comment by luzpaz** [comment]
JFYI, let me know when you have the builds built and I can set the new stable via snapcraft.io per https://github.com/FreeCAD/FreeCAD-snap/blob/master/docs/index.md#how-to-make-a-new-stable-release

**Comment by chennes** [comment]
Hopefully in about 45 minutes...

**Comment by chennes** [comment]
@luzpaz the big moment has arrived... could you please promote the latest build to stable? I believe it worked 😁

**Comment by luzpaz** [comment]
LOL, yea you did it already!

![Screenshot_20230805_181658](https://github.com/FreeCAD/FreeCAD-snap/assets/4140247/dd1c3468-32d9-4ef2-b119-38c8bfc4c4b4)

**Comment by luzpaz** [comment]
Have you tagged 0.22 in FreeCAD master repo yet ? If so then edge and beta should reflect that

**Comment by chennes** [comment]
There won't be a tag for 0.22 (probably ever, since it's really supposed to be 1.0). Those will just pull from master: I think I've got a handle on how the snapcraft.yaml files work now, so I should be able to fight through whatever errors I get in this repo. The freecad-deps repo, on the other hand, timed out after six hours last night, and hadn't even finished building OCCT. So that one is going to be trickier.

**Comment by luzpaz** [comment]
So are we going to call them 1.0 instead ?

**Comment by chennes** [comment]
No, they'll be called 0.22dev.

**Comment by chennes** [comment]
Alright, everything seems to be running bow. Closing this ticket - if/when they break again please start a new Issue. Thanks!

**Comment by luzpaz** [comment]
Note: I can update the Snap page to reflect that edge/nightly and beta/weekly will at times perform very slowly as we're incorporating TPN code. Is that something you think is a good idea ? And perhaps we should recommend a 0.22 build that doesn't have these slow-downs until master is stabilized ?

**Comment by chennes** [comment]
Sure, go for it. Maybe make it generic, though: master is going to move faster basically from now on. The dev versions shouldn't be used in a production environment, even when TNP is merged.
